variables:
  CI_BUILD_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  

before_script: 

  - echo $CI_REGISTRY_IMAGE
  - echo $CI_PROJECT_NAME
  
  - echo "PWD LOCATION IS $PWD"
  - echo "SYSTEM INFO:"
  - cat /etc/os-release
  - cat /etc/hostname


image: docker:20.10.11-alpine3.14

Build project:

  stage: build

  tags:

    - dind-2
  script:

    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_BUILD_IMAGE  .
    - docker push $CI_BUILD_IMAGE

  only:

    - merge_requests
    - master


Deploy to Test ENV:

  stage: deploy

  image: wardove/ansible-kube:1.0.5-ubuntu20.04

  tags:

    - dind-2
  
  variables:

    NAMESPACE: intranet-test

  script: 
    
    - ansible-playbook /ansible/deploy.yml -i /ansible/hosts -vvv

  environment: test

  only:

    - merge_requests
    - master

