---
- name: Kubernetes deployment 
  hosts: kube_entrypoint
  gather_facts: no
  tasks:

    - name: Run kubectl set new image on api entrypoint
      command: kubectl set image -n {{ lookup('env','NAMESPACE') }} deploy {{ lookup('env','CI_PROJECT_NAME') }} {{ lookup('env','CI_PROJECT_NAME') }}={{ lookup('env','CI_BUILD_IMAGE') }}
      become: yes
...
