FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine3.14 as BUILD
RUN mkdir /app && mkdir /build
WORKDIR /app
COPY . .
RUN dotnet publish -c Release -o /build

FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine3.14 AS RUNTIME
RUN mkdir /app
RUN apk add icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
WORKDIR /app
COPY --from=BUILD /build/ .
CMD ["dotnet", "IntraNet.WebApi.dll"]

